version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: socket.io-client
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 4.0.0
  - dependency-name: socket.io
    versions:
    - 3.1.0
  - dependency-name: ejs
    versions:
    - 3.1.5
